<?php

namespace AppBundle\Repository;

/**
 * ShortenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortenerRepository extends \Doctrine\ORM\EntityRepository
{
}
