homepage:
  path: /
  defaults:
    _controller: AppBundle:Default:index

show:
  path: /{short_url}
  defaults:
    _controller: AppBundle:Default:show
  requirements:
          methods: GET

api:
  path: /api/get/{short_url}
  defaults:
    _controller: AppBundle:Default:api
  requirements:
          methods: GET
api_view:
  path: /api/{short_url}/view
  defaults:
    _controller: AppBundle:Default:apiView
  requirements:
          methods: GET
